# Generated by Django 2.1.3 on 2018-11-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Choose a tag', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Enter new task', max_length=500, verbose_name='Task')),
                ('due_by', models.DateTimeField()),
                ('complete', models.BooleanField(default=False, null=True)),
                ('due_status', models.CharField(blank=True, choices=[('ny', 'Not yet due'), ('dt', 'Due today'), ('od', 'Overdue')], default='ny', max_length=2)),
                ('priority', models.CharField(choices=[('1', '1 - High'), ('2', '2 - Medium'), ('3', '3 - Low')], default='2', max_length=1)),
                ('tag', models.ManyToManyField(help_text='Select a tag for this task', to='beno.Tag')),
            ],
            options={
                'ordering': ['priority', '-due_by'],
            },
        ),
    ]
