# Generated by Django 2.1.3 on 2018-11-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beno', '0003_auto_20181128_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
