# Generated by Django 2.1.3 on 2018-11-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beno', '0003_task_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(help_text='Enter new task', max_length=300, verbose_name='Task'),
        ),
    ]
