# Generated by Django 2.1.3 on 2018-11-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beno', '0004_auto_20181118_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Select a category for this task', to='beno.Category'),
        ),
    ]
