# Generated by Django 2.1.3 on 2018-12-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beno', '0004_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
