# Generated by Django 2.1.3 on 2018-11-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beno', '0006_auto_20181118_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_by', 'priority']},
        ),
    ]
