# Generated by Django 2.1.3 on 2018-11-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beno', '0008_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_by', 'priority'], 'permissions': (('can_mark_completed', 'Mark task as complete'),)},
        ),
    ]
